# Copyright (c) 2023-present Pi Dash Software, Inc. and contributors
# SPDX-License-Identifier: AGPL-3.0-only
# See the LICENSE file for details.

RESTRICTED_WORKSPACE_SLUGS = [
    "404",
    "accounts",
    "api",
    "create-workspace",
    "god-mode",
    "installations",
    "invitations",
    "onboarding",
    "profile",
    "spaces",
    "workspace-invitations",
    "password",
    "flags",
    "monitor",
    "monitoring",
    "ingest",
    "pi-dash-pro",
    "pi-dash-ultimate",
    "enterprise",
    "pi-dash-enterprise",
    "disco",
    "silo",
    "chat",
    "calendar",
    "drive",
    "channels",
    "upgrade",
    "billing",
    "sign-in",
    "sign-up",
    "signin",
    "signup",
    "config",
    "live",
    "admin",
    "m",
    "import",
    "importers",
    "integrations",
    "integration",
    "configuration",
    "initiatives",
    "initiative",
    "config",
    "workflow",
    "workflows",
    "epics",
    "epic",
    "story",
    "mobile",
    "dashboard",
    "desktop",
    "onload",
    "real-time",
    "one",
    "pages",
    "mobile",
    "business",
    "pro",
    "settings",
    "monitor",
    "license",
    "licenses",
    "instances",
    "instance",
]

# Lifecycle ordering shared by API sorting, grouping, filtering, analytics,
# and maintenance tasks. Triage is intentionally excluded because it has its
# own manager and intake workflow.
STATE_GROUP_ORDER = (
    "backlog",
    "unstarted",
    "started",
    "review",
    "test",
    "completed",
    "cancelled",
)

OPEN_STATE_GROUPS = STATE_GROUP_ORDER[:-2]
ACTIVE_STATE_GROUPS = STATE_GROUP_ORDER[1:-2]
CLOSED_STATE_GROUPS = STATE_GROUP_ORDER[-2:]
