# Generated by Codex on 2026-05-23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0134_issueagentticker_disarm_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
    ]
