# Generated by Codex on 2026-05-23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0136_backfill_default_project"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                fields=("workspace",),
                condition=models.Q(is_default=True, deleted_at__isnull=True),
                name="project_unique_default_per_workspace",
            ),
        ),
    ]
