services:
  web:
    image: ${DOCKERHUB_USER:-local}/apple-pi-dash-frontend:${APP_RELEASE:-latest}
    build:
      context: ../../
      dockerfile: apps/web/Dockerfile.web

  space:
    image: ${DOCKERHUB_USER:-local}/apple-pi-dash-space:${APP_RELEASE:-latest}
    build:
      context: ../../
      dockerfile: apps/space/Dockerfile.space

  admin:
    image: ${DOCKERHUB_USER:-local}/apple-pi-dash-admin:${APP_RELEASE:-latest}
    build:
      context: ../../
      dockerfile: apps/admin/Dockerfile.admin

  live:
    image: ${DOCKERHUB_USER:-local}/apple-pi-dash-live:${APP_RELEASE:-latest}
    build:
      context: ../../
      dockerfile: apps/live/Dockerfile.live

  api:
    image: ${DOCKERHUB_USER:-local}/apple-pi-dash-backend:${APP_RELEASE:-latest}
    build:
      context: ../../apps/api
      dockerfile: Dockerfile.api

  proxy:
    image: ${DOCKERHUB_USER:-local}/apple-pi-dash-proxy:${APP_RELEASE:-latest}
    build:
      context: ../../apps/proxy
      dockerfile: Dockerfile.ce
