# Copyright (c) 2023-present Pi Dash Software, Inc. and contributors
# SPDX-License-Identifier: AGPL-3.0-only
# See the LICENSE file for details.

# Generated by Django 4.2.30 on 2026-06-11 22:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('db', '0148_issue_created_via'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seq', models.BigIntegerField(default=0)),
                ('kind', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('tool_call', 'Tool call'), ('tool_result', 'Tool result'), ('error', 'Error')], max_length=16)),
                ('display_content', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('streaming', 'Streaming'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='completed', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'assistant_message',
                'ordering': ('seq',),
            },
        ),
        migrations.CreateModel(
            name='AssistantThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'assistant_thread',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='UserLLMConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_kind', models.CharField(choices=[('openai_compatible', 'OpenAI-compatible'), ('anthropic', 'Anthropic')], default='openai_compatible', max_length=32)),
                ('base_url', models.URLField(blank=True, default='', max_length=500)),
                ('model_name', models.CharField(blank=True, default='', max_length=255)),
                ('api_key_encrypted', models.BinaryField(blank=True, null=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_llm_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assistant_user_llm_config',
            },
        ),
        migrations.CreateModel(
            name='AssistantTurn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('model_messages', models.JSONField(blank=True, null=True)),
                ('usage', models.JSONField(blank=True, null=True)),
                ('model_used', models.CharField(blank=True, default='', max_length=255)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('error_detail', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='assistant.assistantthread')),
                ('user_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assistant.assistantmessage')),
            ],
            options={
                'db_table': 'assistant_turn',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddField(
            model_name='assistantthread',
            name='active_turn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assistant.assistantturn'),
        ),
        migrations.AddField(
            model_name='assistantthread',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_threads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assistantthread',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_threads', to='db.workspace'),
        ),
        migrations.AddField(
            model_name='assistantmessage',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='assistant.assistantthread'),
        ),
        migrations.AddField(
            model_name='assistantmessage',
            name='turn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='assistant.assistantturn'),
        ),
        migrations.CreateModel(
            name='AssistantEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('seq', models.BigIntegerField(default=0)),
                ('kind', models.CharField(max_length=64)),
                ('message_id', models.UUIDField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='assistant.assistantthread')),
                ('turn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='assistant.assistantturn')),
            ],
            options={
                'db_table': 'assistant_event',
                'ordering': ('seq',),
            },
        ),
        migrations.AddIndex(
            model_name='assistantturn',
            index=models.Index(fields=['thread', 'created_at'], name='asst_turn_thread_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantturn',
            index=models.Index(fields=['status', 'started_at'], name='asst_turn_status_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantthread',
            index=models.Index(fields=['workspace', 'user', '-updated_at'], name='asst_thread_ws_user_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantmessage',
            index=models.Index(fields=['thread', 'seq'], name='asst_msg_thread_seq_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantevent',
            index=models.Index(fields=['thread', 'seq'], name='asst_event_thread_seq_idx'),
        ),
    ]
