//! `.pidash/context.md` writer — leaves a project-association marker in the
//! runner's working directory so a human (or another tool) can tell which
//! Pi Dash workspace/project a checkout is linked to.
//!
//! Called from the enroll flows in `cli::connect` after the cloud-side
//! enrollment and local config write both succeed. Failures here are
//! non-fatal: the runner is already live and re-running `pidash connect` is
//! not a viable recovery path (the enrollment token is single-use).

use std::fs;
use std::io;
use std::path::{Path, PathBuf};

/// Fields written into `.pidash/context.md`. Everything except `runner_name`
/// and the timestamp identifies *where* this checkout is linked; the runner
/// fields identify *which* local runner owns the link.
#[derive(Debug, Clone)]
pub struct ContextFields<'a> {
    pub cloud_url: &'a str,
    pub workspace_slug: &'a str,
    pub project_identifier: &'a str,
    pub runner_name: &'a str,
    pub runner_id: uuid::Uuid,
}

/// Write (or overwrite) `<working_dir>/.pidash/context.md`. Creates the
/// working dir and the `.pidash/` subdir if missing. Returns the written
/// path on success.
///
/// Overwrite-on-rewrite is intentional: re-running enrollment against the
/// same workdir should refresh the marker (e.g. timestamp, runner_id after
/// a revive). Operators wanting an audit trail can rely on git history or
/// the cloud side.
pub fn write_context_md(working_dir: &Path, fields: &ContextFields<'_>) -> io::Result<PathBuf> {
    let dir = working_dir.join(".pidash");
    fs::create_dir_all(&dir)?;
    let path = dir.join("context.md");
    let body = render(fields, &chrono::Utc::now().to_rfc3339());
    fs::write(&path, body)?;
    Ok(path)
}

fn render(fields: &ContextFields<'_>, linked_at_rfc3339: &str) -> String {
    format!(
        "# Pi Dash workspace context\n\
         \n\
         This directory is linked to a Pi Dash project. The Pi Dash runner uses\n\
         this file to mark the working directory as connected to the project\n\
         and cloud below. Generated by `pidash connect`; safe to delete if you\n\
         unlink the runner, but normally leave it in place.\n\
         \n\
         - Cloud: {cloud}\n\
         - Workspace: {workspace}\n\
         - Project: {project}\n\
         - Runner: {runner_name} ({runner_id})\n\
         - Linked at: {linked_at}\n",
        cloud = fields.cloud_url,
        workspace = fields.workspace_slug,
        project = fields.project_identifier,
        runner_name = fields.runner_name,
        runner_id = fields.runner_id,
        linked_at = linked_at_rfc3339,
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;
    use uuid::Uuid;

    fn fixed_fields() -> (String, String, String, String, Uuid) {
        (
            "https://pidash.example.com".to_string(),
            "acme".to_string(),
            "PDASHOSS01".to_string(),
            "laptop-1".to_string(),
            Uuid::parse_str("12345678-1234-5678-1234-567812345678").unwrap(),
        )
    }

    #[test]
    fn writes_context_md_inside_pidash_subdir() {
        let tmp = tempdir().unwrap();
        let (cloud, ws, proj, runner, rid) = fixed_fields();
        let path = write_context_md(
            tmp.path(),
            &ContextFields {
                cloud_url: &cloud,
                workspace_slug: &ws,
                project_identifier: &proj,
                runner_name: &runner,
                runner_id: rid,
            },
        )
        .unwrap();
        assert_eq!(path, tmp.path().join(".pidash").join("context.md"));
        assert!(path.is_file());
    }

    #[test]
    fn creates_working_dir_if_missing() {
        let tmp = tempdir().unwrap();
        let wd = tmp.path().join("not-yet-there");
        let (cloud, ws, proj, runner, rid) = fixed_fields();
        write_context_md(
            &wd,
            &ContextFields {
                cloud_url: &cloud,
                workspace_slug: &ws,
                project_identifier: &proj,
                runner_name: &runner,
                runner_id: rid,
            },
        )
        .unwrap();
        assert!(wd.join(".pidash").join("context.md").is_file());
    }

    #[test]
    fn body_contains_all_identifying_fields() {
        let (cloud, ws, proj, runner, rid) = fixed_fields();
        let body = render(
            &ContextFields {
                cloud_url: &cloud,
                workspace_slug: &ws,
                project_identifier: &proj,
                runner_name: &runner,
                runner_id: rid,
            },
            "2026-05-11T00:00:00+00:00",
        );
        assert!(body.contains("https://pidash.example.com"));
        assert!(body.contains("acme"));
        assert!(body.contains("PDASHOSS01"));
        assert!(body.contains("laptop-1"));
        assert!(body.contains("12345678-1234-5678-1234-567812345678"));
        assert!(body.contains("2026-05-11T00:00:00+00:00"));
    }

    #[test]
    fn rewrite_overwrites_previous_contents() {
        let tmp = tempdir().unwrap();
        let (cloud, ws, proj, runner, rid) = fixed_fields();
        let f1 = ContextFields {
            cloud_url: &cloud,
            workspace_slug: &ws,
            project_identifier: &proj,
            runner_name: &runner,
            runner_id: rid,
        };
        write_context_md(tmp.path(), &f1).unwrap();
        let other_runner = "laptop-2".to_string();
        let f2 = ContextFields {
            cloud_url: &cloud,
            workspace_slug: &ws,
            project_identifier: &proj,
            runner_name: &other_runner,
            runner_id: rid,
        };
        write_context_md(tmp.path(), &f2).unwrap();
        let body = fs::read_to_string(tmp.path().join(".pidash").join("context.md")).unwrap();
        assert!(body.contains("laptop-2"));
        assert!(!body.contains("laptop-1"));
    }
}
