[package]
name = "pidash-db"
version = "0.1.0"
edition = "2021"

[dependencies]
pidash-types = { path = "../types" }
thiserror = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sqlx = { version = "0.8", features = ["postgres", "runtime-tokio"] }
sea-query = { version = "0.32", default-features = false, features = ["backend-postgres"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
