# Generated by Django 4.2.30 on 2026-04-30 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0008_connection_replaces_machine_token'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='agentrun',
            new_name='agent_run_runner__1237dd_idx',
            old_name='agentrun_runner_status_idx',
        ),
        migrations.RenameIndex(
            model_name='agentrun',
            new_name='agent_run_owner_i_75b982_idx',
            old_name='agentrun_owner_status_idx',
        ),
        migrations.RenameIndex(
            model_name='agentrun',
            new_name='agent_run_workspa_987ef0_idx',
            old_name='agentrun_ws_status_idx',
        ),
        migrations.RenameIndex(
            model_name='approvalrequest',
            new_name='agent_run_a_agent_r_6fe098_idx',
            old_name='approval_run_status_idx',
        ),
        migrations.RenameIndex(
            model_name='connection',
            new_name='connection_workspa_806721_idx',
            old_name='machine_tok_workspc_revoked_idx',
        ),
        migrations.RenameIndex(
            model_name='connection',
            new_name='connection_created_268384_idx',
            old_name='machine_tok_creator_revoked_idx',
        ),
        migrations.RenameIndex(
            model_name='runner',
            new_name='runner_owner_i_cd64a7_idx',
            old_name='runner_owner_status_idx',
        ),
        migrations.RenameIndex(
            model_name='runner',
            new_name='runner_workspa_243566_idx',
            old_name='runner_ws_status_idx',
        ),
        migrations.AddIndex(
            model_name='pod',
            index=models.Index(fields=['project', 'is_default'], name='pod_project_is_def_idx'),
        ),
    ]
