//! Fernet encryption for `InstanceConfiguration` secrets.
//!
//! Port of `apps/api/pi_dash/license/utils/encryption.py`. The key schedule
//! is PBKDF2-HMAC-SHA256 over the Django `SECRET_KEY` (100 000 rounds, salt
//! `b"salt"`, 32 bytes, URL-safe base64) and the payload cipher is standard
//! Fernet, so tokens written by Python decrypt here and vice versa.
//!
//! Failure semantics are ported exactly, including the wart: a decryption
//! failure is logged and yields `""` rather than an error, so a rotated or
//! corrupt secret reads as an empty value instead of failing the request.
//! (Ported bug, kept for byte-for-byte behavior.)

use base64::{engine::general_purpose::URL_SAFE, Engine as _};

const PBKDF2_ROUNDS: u32 = 100_000;
const PBKDF2_SALT: &[u8] = b"salt";

/// Derive the Fernet key string from a Django `SECRET_KEY`, exactly like
/// Python's `derive_key`: `urlsafe_b64encode(pbkdf2_hmac("sha256", secret,
/// b"salt", 100_000))`.
pub fn derive_fernet_key(secret_key: &str) -> String {
    let mut dk = [0u8; 32];
    pbkdf2::pbkdf2_hmac::<sha2::Sha256>(secret_key.as_bytes(), PBKDF2_SALT, PBKDF2_ROUNDS, &mut dk);
    URL_SAFE.encode(dk)
}

/// Encrypt/decrypt with one secret. Build from the resolved `SECRET_KEY`
/// (see [`crate::config::settings`]) and share it; construction is cheap and
/// the type is `Clone`. `Debug` is redacted: the key never reaches logs.
#[derive(Clone)]
pub struct Keyring {
    fernet: Option<fernet::Fernet>,
}

impl std::fmt::Debug for Keyring {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Keyring")
            .field("usable", &self.fernet.is_some())
            .finish()
    }
}

impl Keyring {
    /// Build from a secret. An undecodable/empty secret yields a keyring
    /// whose decrypts all fail closed to `""` (never a panic).
    pub fn from_secret(secret_key: &str) -> Self {
        let fernet = fernet::Fernet::new(&derive_fernet_key(secret_key));
        Self { fernet }
    }

    /// Build from the `SECRET_KEY` process env var; missing or empty env
    /// behaves like [`Keyring::from_secret`] with `""`.
    pub fn from_env() -> Self {
        Self::from_secret(&std::env::var("SECRET_KEY").unwrap_or_default())
    }

    /// Decrypt a stored value. Empty input yields `""` (Python's falsy
    /// short-circuit); failure yields `""` after a warn log (the ported bug).
    pub fn decrypt(&self, encrypted: &str) -> String {
        if encrypted.is_empty() {
            return String::new();
        }
        match self.fernet.as_ref() {
            Some(f) => match f.decrypt(encrypted) {
                Ok(bytes) => String::from_utf8_lossy(&bytes).into_owned(),
                Err(err) => {
                    tracing::warn!("config decrypt failed; returning empty: {err}");
                    String::new()
                }
            },
            None => {
                tracing::warn!("config decrypt without a usable key; returning empty");
                String::new()
            }
        }
    }

    /// Encrypt a value for storage. Empty input yields `""`; with no usable
    /// key the result is `""` (mirrors Python's `log_exception` + `""`).
    pub fn encrypt(&self, value: &str) -> String {
        if value.is_empty() {
            return String::new();
        }
        match self.fernet.as_ref() {
            Some(f) => f.encrypt(value.as_bytes()),
            None => {
                tracing::warn!("config encrypt without a usable key; returning empty");
                String::new()
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const TEST_SECRET: &str = "test-secret-key";

    #[test]
    fn derived_key_matches_python() {
        // Generated by apps/api/pi_dash/license/utils/encryption.py's
        // derive_key("test-secret-key") under cryptography 43.0.3.
        assert_eq!(
            derive_fernet_key(TEST_SECRET),
            "g7t9c4Ah6MVui10RpWHy8k1gT-_hCE8qhrHSqX0so2k="
        );
    }

    #[test]
    fn decrypts_python_generated_token() {
        // Fernet-encrypted by Python's encrypt_data("s3cret") with the key
        // above. Plain Fernet decrypt has no TTL check, so the vector is
        // stable and proves cross-implementation compatibility.
        let token = "gAAAAABquBQHQm9rFi-dMhCcfhPi9PnEVAIbRNG3Czhzb2dsBOE6Zo4HRnwUzlMJPG7-Sx_EQdZsfkLM1VqFkyexwgnbGREgDA==";
        assert_eq!(Keyring::from_secret(TEST_SECRET).decrypt(token), "s3cret");
    }

    #[test]
    fn round_trip() {
        let k = Keyring::from_secret(TEST_SECRET);
        let token = k.encrypt("s3cret");
        assert!(!token.is_empty());
        assert_eq!(k.decrypt(&token), "s3cret");
    }

    #[test]
    fn empty_and_failure_yield_empty_string() {
        let k = Keyring::from_secret(TEST_SECRET);
        assert_eq!(k.decrypt(""), "");
        assert_eq!(k.encrypt(""), "");
        // Corrupt token and wrong-key token both degrade to "".
        assert_eq!(k.decrypt("not-a-token"), "");
        assert_eq!(
            Keyring::from_secret("other-secret").decrypt(&k.encrypt("s3cret")),
            ""
        );
    }
}
